"""Module for the handling of pixel tables generated by Hicona.

The module contains:
- `TableIntervals`: class for the handling of table intervals.
- `Table`: base class for all table types in Hicona.
- `RawTable`: class for the handling of raw pixel tables.
- `HiconaTable`: class for the handling of processed pixel tables.
"""

from collections.abc import Iterable
from math import dist
import json

import cooler
import numpy as np
import pandas as pd

import hicona.hicona_cooler as hicooler  # For circular import
from .plotting import plot_alpha_grid
from .processing.processing_flow import ProcessingFlow
from .uris import Uris
from .utils.dtypes import AlphaModType, OptionalAxes, PdChunks
from .utils.hdf5_ops import fetch_chunk, get_attrs, get_table_size
from .utils.misc import GenomicRegion
from .utils.numeric import round_half_up


FULL_TABLE = "full_table"


class TableIntervals:
    """Class to handle chunk fetching from pixel tables.

    Chunk fetching is handled by storing indexes for each fixed size chunk.
    When iterating through the table, each chunk is fetched and indexed.
    When the number of fetched rows covers the full chunk size (or if no more
    chunks are available), the chunk is returned and the process is repeated.

    The class also implements operations such as subsetting and boolean logic
    among indexes to facilitate the selection of complex intervals.

    Parameters
    ----------
    table : Table
        The table object to which the intervals belong.
    indexes : list[pd.Index], optional
        List of indexes for each chunk. If not provided, a full index is
        created for each chunk (all pixels are iterated). Default is None.
    interval_str : str, optional
        String representation of the intervals, that is a description of the
        operations used to generate the indexes. If not provided, it is set
        to `full_table`. Default is None.
    """

    def __init__(
        self,
        table: "Table",
        indexes: list[pd.Index] | None = None,
        interval_str: str | None = None,
    ):

        if bool(indexes) != bool(interval_str):
            raise ValueError(
                "Both indexes and interval_str must be provided or neither."
            )

        self._table = table
        self._indexes = indexes or self._initial_index()
        self._interval_str = interval_str or FULL_TABLE
        self._size: int = 0  # Random initialization value

        self.update_size()

    def __str__(self) -> str:

        return self._interval_str

    def __or__(self, other: "TableIntervals") -> "TableIntervals":

        iterator = zip(self._indexes, other.get_indexes())
        new_intervals = [i.join(j, how="outer") for i, j in iterator]
        new_repr = f"({self._interval_str} | {other._interval_str})"

        return TableIntervals(self._table, new_intervals, new_repr)

    def __and__(self, other: "TableIntervals") -> "TableIntervals":

        iterator = zip(self._indexes, other.get_indexes())
        new_intervals = [i.join(j, how="inner") for i, j in iterator]
        new_repr = f"({self._interval_str} & {other._interval_str})"

        return TableIntervals(self._table, new_intervals, new_repr)

    def _initial_index(self) -> list[pd.Index]:
        """Return an index of the complete table split into chunks."""

        table_size = get_table_size(*self._table.uris.hdf5_uris())
        chunk_size = self._table.chunk_size

        num_full_chunks, partial_chunk_size = divmod(table_size, chunk_size)
        full_chunk_ind = pd.Index(range(0, chunk_size), dtype="int32")
        part_chunk_ind = pd.Index(range(0, partial_chunk_size), dtype="int32")

        return [full_chunk_ind] * num_full_chunks + [part_chunk_ind]

    @property
    def size(self) -> int:
        """Return the size of the complete table or the subset."""

        return self._size

    def update_size(self):
        """Update the size of the complete table or the subset."""

        self._size = sum(len(c) for c in self._indexes)

    def subset(self, region: str, both: bool = True) -> "TableIntervals":
        """Subset a full genomic table to a region of interest."""

        # NOTE: currently not allowing the subset of subsets because it
        #       is not clear how to handle the interval_str in that case.
        #       Might be implemented in the future if needed.
        if self._interval_str != FULL_TABLE:
            raise ValueError("Cannot subset a subset. Use boolean operators instead.")

        new_repr = f"{region}({'+' if both else '-'})"

        gen_region = GenomicRegion(region)
        gen_region.snap_to_bin(self._table.bin_size)
        query_str = gen_region.to_query(both)

        pd_chunks = self._table.chunks(annotated=True)
        new_indexes = [c.query(query_str).index for c in pd_chunks]

        return TableIntervals(self._table, new_indexes, new_repr)

    def get_indexes(self) -> Iterable[pd.Index]:
        """Return the indexes of the table or the subset."""

        for index in self._indexes:
            yield index


class Table:
    """Base class for all table types in Hicona."""

    def __init__(
        self,
        uris: Uris,
        intervals: TableIntervals | None = None,
        bin_size: int | None = None,
        chunk_size: int | None = None,
    ):

        def reconstruct_flow(uris: Uris) -> ProcessingFlow:
            """Reconstruct the ProcessingFlow object from the store."""

            # TODO: check whether the table is valid and skip if not
            tab_attrs = get_attrs(*uris.hdf5_uris())
            flow_json = json.loads(tab_attrs["process_info"])
            return ProcessingFlow.from_json(flow_json)

        def get_bin_size(uris: Uris) -> int:
            """Return the bin size of the cooler."""

            parent_cool = hicooler.HiconaCooler(uris.cooler_uri())
            return parent_cool.binsize

        def get_chunk_size(uris: Uris) -> int:
            """Return the default chunk size for the table."""

            parent_cool = hicooler.HiconaCooler(uris.cooler_uri())
            return parent_cool.chunk_size

        self._uris = uris
        self._flow = reconstruct_flow(uris)
        self._bin_size = bin_size or get_bin_size(uris)
        self._chunk_size = chunk_size or get_chunk_size(uris)
        self._intervals = intervals or TableIntervals(self)

    @property
    def bin_size(self) -> int:
        """Resolution of the original cooler (size of the bins in bp)."""
        return self._bin_size

    @property
    def chunk_size(self) -> int:
        """Size of the chunks to retrieve during iteration."""
        return self._chunk_size

    @property
    def flow(self) -> ProcessingFlow:
        """ProcessingFlow object containing all processing information."""
        return self._flow

    @property
    def uris(self) -> Uris:
        """Uris object containing all table uris."""
        return self._uris

    @property
    def size(self) -> int:
        """Total number of pixels in the table."""
        return self._intervals.size

    def chunks(
        self,
        columns: Iterable[str] | None = None,
        annotated: bool = False,
    ) -> PdChunks:
        """Returns an iterator of table chunks (as pandas DataFrames).

        Parameters
        ----------
        columns: Iterable[str] or None, optional
            If provided, only fetch the specified columns. Default is None.
        annotated: bool, optional
            Whether to annotate with the bin information. Default is False.

        Returns
        -------
        An iterator of table chunks (as pandas DataFrames).
        """

        def prepare_chunk(chunk, bins=None, columns=None) -> pd.DataFrame:
            """Prepare the chunk for output with annotation of filtering."""

            if bins is not None:
                chunk = cooler.annotate(chunk, bins)
            if columns:
                chunk = chunk[columns]

            return chunk

        # Fetch bins if needed for annotation
        cool = hicooler.HiconaCooler(self.uris.cooler_uri())
        bins = cool.bins()[:] if annotated else None

        # Growing list to concat to create the full chunk
        chunk_parts: list[pd.DataFrame] = []

        # Iterate all indexes
        indexes = self._intervals.get_indexes()
        for num, index in enumerate(indexes):

            # Skip chunk if no pixels from it need to be kept
            if len(index) == 0:
                continue

            # Fetch and index the chunk
            lower = num * self.chunk_size
            upper = (num + 1) * self.chunk_size
            chunk = fetch_chunk(*self.uris.hdf5_uris(), lower, upper)
            chunk = chunk.iloc[index]

            # Add kept pixels to the growing list
            chunk_parts.append(chunk)

            # Yield the chunk if it is complete
            # Save extra pixels for the next chunk
            new_chunks_size = sum(len(c) for c in chunk_parts)
            if new_chunks_size >= self.chunk_size:

                out_chunk = pd.concat(chunk_parts)

                chunk_parts = [out_chunk.iloc[self.chunk_size :]]
                out_chunk = out_chunk.iloc[: self.chunk_size]

                yield prepare_chunk(out_chunk, bins, columns)

        # Yield the remaining pixels as an incomplete chunk
        if len(chunk_parts) > 0:
            yield prepare_chunk(pd.concat(chunk_parts), bins, columns)

    def dataframe(
        self,
        columns: Iterable[str] | None = None,
        annotated: bool = False,
    ) -> pd.DataFrame:
        """Return all table chunks in a single pandas DataFrame.

        NOTE: This operation can be rather expensive in terms of memory,
        especially for large or non subsetted tables.

        Parameters
        ----------
        columns: Iterable[str], optional
            If provided, only fetch the specified columns. Default is None.
        annotated: bool, optional
            Whether to annotate with the bin information. Default is False.

        Returns
        -------
        A pandas DataFrame with all table pixels.
        """

        iterator = self.chunks(columns, annotated)
        return pd.concat(iterator).reset_index(drop=True)


class RawTable(Table):
    """Specialized class for the handling of raw pixel tables."""

    def reset_index(self):
        """Regenerate the indexes (useful after table resizing)."""

        self._intervals = TableIntervals(self)
        # TODO: check because this might not work as expected
        # due to the way the table is resized in the hdf5 file


class HiconaTable(Table):
    """Class for sparsified pixel table handling.

    Class implementing everything needed to handle sparsified pixel tables,
    such as pixel fetching, subsetting, boolean operations and analysis.

    Instances of this class should be created via the
    `HiconaCooler.fetch_table` method rather than directly.

    Parameters
    ----------
    uris : Uris
        Uris object specifying the location of the table in the cooler file.
    intervals : TableIntervals, optional
        TableIntervals object specifying the parts of the table to consider.
        If not provided, the full table is considered. Default is None.
    """

    def __init__(self, uris: Uris, intervals: TableIntervals | None = None):
        super().__init__(uris, intervals=intervals)

    @property
    def region(self) -> str:
        """Return the region of the table or the subset."""
        return str(self._intervals)

    def subset(self, region: str, both: bool = True) -> "HiconaTable":
        """Return a subset of the table based on pixel genomic regions.

        Parameters
        ----------
        region : str
            Genomic region to keep. It must be a string in bed-like format,
            such as "chr1 10000 200000" or just "chr1".
        both : bool, optional
            Whether to keep a pixel only if both of its bins are in the
            specified region. If False, keep a pixel if at least one of its
            bins is in the region. Default is True.

        Returns
        -------
        HiconaTable :
            A new HiconaTable object with the subset of the original table.
        """

        new_intervals = self._intervals.subset(region, both)
        return HiconaTable(self.uris, new_intervals)

    def _same_source_check(self, other: "HiconaTable"):
        """Return whether the two tables have the same source cooler."""

        same_uris = self.uris.cooler_uri() == other.uris.cooler_uri()
        same_size = self.chunk_size == other.chunk_size

        if not same_uris or not same_size:
            raise ValueError("Tables must have the same source cooler and chunk size.")

    def __or__(self, other: "HiconaTable") -> "HiconaTable":

        self._same_source_check(other)
        new_intervals = self._intervals | other._intervals
        return HiconaTable(self.uris, new_intervals)

    def __and__(self, other: "HiconaTable") -> "HiconaTable":

        self._same_source_check(other)
        new_intervals = self._intervals & other._intervals
        return HiconaTable(self.uris, new_intervals)

    def get_alpha_grid(
        self,
        alpha_mod: AlphaModType = "min",
        decimals: int = 3,
        verbose: bool = True,
    ) -> "AlphaGrid":
        """Return a grid for the table filtered at different alpha values.

        Compute the number and fraction of nodes and edges remaining in the
        table when filtered at different alpha values.
        For the threshold selection procedure see the `AlphaGrid` class.

        Parameters
        ----------
        alpha_mod : "min" or "max", optional
            The alpha mode to use for filtering. (Default is "min")
        decimals : int, optional
            The number of decimal positions to consider when computing the
            grid. (Default is 3)
        verbose : bool, optional
            Whether to log the progress of the computation. (Default is True)

        Returns
        -------
        AlphaGrid :
            An AlphaGrid object with the statistics for each alpha value.
        """

        return AlphaGrid(self, alpha_mod, decimals, verbose)


class AlphaGrid:
    """Class for the computation of the optimal alpha value for filtering.

    During class initialization, the optimal alpha value is computed using
    the following steps:

    - define a grid of alpha values centered around the current optimal
      and spaced in order to cover 1 unit of previous decimal position.
    - for each alpha value, filter the table and compute the remaining
      fraction of edges and nodes.
    - for each alpha compute the Euclidean distance from point ``(1, 0)``
      in the space ``x: fraction of nodes``, ``y: fraction of edges``.
    - set as new optimal alpha the one minimizing the Euclidean distance.
    - move to the next decimal position and repeat the procedure.

    Parameters
    ----------
    table : HiconaTable
        The table for which the optimal alpha value is computed.
    alpha_mod : "min" or "max"
        The alpha mode to use for filtering.
    decimals : int
        The number of decimal positions to consider when computing the grid.
    verbose : bool
        Whether to log the progress of the computation.
    """

    def __init__(
        self,
        table: HiconaTable,
        alpha_mod: AlphaModType,
        decimals: int,
        verbose: bool,
    ):
        self._table = table
        self._alpha_mod = alpha_mod
        self._decimals = decimals
        self._alpha_grid = self._compute_grid(decimals, verbose)

    def _get_stats(self, thr: float) -> tuple[int, int]:
        """Return number of nodes and edges in a table filtered by alpha."""

        nodes: set = set()
        edges: int = 0

        alpha_col = "alpha_" + self._alpha_mod
        for chunk in self._table.chunks():
            chunk = chunk.query(f"{alpha_col} <= {thr}")

            nodes |= set(chunk["bin1_id"]) | set(chunk["bin2_id"])
            edges += len(chunk)

        return len(nodes), edges

    def _get_alpha_pts(self, thresholds: list[float]) -> pd.DataFrame:
        """Return dataframe with filtering statistics for a threshold grid."""
        # NOTE: Assumed that alpha thresholds are in decreasing order.

        res_list = []

        # Define normalization values
        tot_nodes, tot_edges = self._get_stats(1)

        # Iterate over each alpha value
        for alpha in thresholds:
            num_nodes, num_edges = self._get_stats(alpha)
            res_list.append(
                {
                    "alpha": alpha,
                    "nodes_n": num_nodes,
                    "edges_n": num_edges,
                    "nodes_f": (frac_nodes := num_nodes / tot_nodes),
                    "edges_f": (frac_edges := num_edges / tot_edges),
                    "eu_dist": dist((1, 0), (frac_nodes, frac_edges)),
                }
            )

        return pd.DataFrame(res_list)

    def _compute_grid(self, decimals: int, verbose: bool) -> pd.DataFrame:
        """Return the grid containing the statistics for each alpha value."""

        # Initialize optimal alpha and result container
        opt_alpha = 0.5  # Middle of initial search space 0-1
        num_points = 21  # Must be 10x + 1 to guarantee 1 unit span
        alpha_vals = []

        for pos in range(decimals):
            if verbose:
                print(f"Optimal alpha: computing decimal {pos+1}")

            # Define the grid of alpha values to test
            step = 0.5 * 10 ** (-pos)
            grid = np.linspace(opt_alpha + step, opt_alpha - step, num_points)
            grid = [a for a in grid if 0 <= a <= 1]

            # Compute the new statistics, then update optimal alpha
            new_pts = self._get_alpha_pts(grid)
            opt_alpha = self._get_minimal_dist(new_pts)
            alpha_vals.append(new_pts)

        return pd.concat(alpha_vals).reset_index()

    @staticmethod
    def _get_minimal_dist(table: pd.DataFrame) -> float:
        """Return the alpha value minimizing the Euclidean distance."""

        position = table["eu_dist"].idxmin()
        if not isinstance(position, int):
            raise ValueError("Non numeric index. This should not happen.")
        return table["alpha"].iloc[position]

    @property
    def optimal_alpha(self) -> float:
        """Return the optimal alpha value for filtering the pixel table."""

        optimal_value = self._get_minimal_dist(self._alpha_grid)
        return round_half_up(optimal_value, self._decimals)

    def plot(
        self,
        img_path: str | None = None,
        show: bool = False,
    ) -> OptionalAxes:
        """Plot the grid object.

        Plot and/or show the grid of alpha values tested when computing the
        optimal alpha value for pixel filtering. The plot has the fraction
        of retained nodes on the ``x`` axis and the fraction of retained
        edges on the ``y`` axis.

        Parameters
        ---------
        img_path : str or None, optional
            If provided, path to save the plot to. (default is None)
        show : bool, optional
            If True, display the plot in a :py:mod:`matplotlib` window.
            (default is False)

        Returns
        -------
        matplotlib.axes.Axes or None :
            If ``show`` is False, return plot axes. Otherwise, return None.
        """

        plot_alpha_grid(self._alpha_grid, img_path, show)


# def annotation_dynamics(self, annot: str) -> pd.DataFrame:
#     """Placeholder"""

#     def process_table(table, lower, upper):
#         """Placeholder"""

#         ann1, ann2, alpha_col = table.columns  # Assumed for convenience

#         filt_table = table.loc[table[alpha_col] <= upper]
#         filt_table = filt_table.query(f"{alpha_col} > {lower}")

#         out = filt_table.groupby([ann1, ann2]).count()
#         out.reset_index(inplace=True)
#         out["alpha"] = upper

#         return out

#     def compute_quantiles(table):
#         """Placeholder"""

#         curve = pd.Series()
#         total = 0
#         for chunk in table.get_chunks():
#             total += len(chunk)
#             vals = chunk.groupby("alpha_min")["count"].count()
#             curve = curve.combine(vals, lambda x, y: x + y, fill_value=0)

#         num_pix = curve.sum()
#         cumulative = curve.cumsum()
#         quantiles = [0.1 * i * num_pix for i in range(1, 11)]
#         thrs = [cumulative[cumulative >= q].index[0] for q in quantiles]
#         thrs = [0] + thrs  # Added after since first index is not 0

#         return thrs

#     alphas = compute_quantiles(self)
#     interv = [(alphas[i], alphas[i + 1]) for i in range(len(alphas) - 1)]

#     parent_store = self._table_uri.split("hicona_tables")[0].strip("/")
#     parent_location = self._store_uri
#     if parent_store:  # Non empty -> multires
#         parent_location += f"::{parent_store}"

#     parent_cooler = cooler.Cooler(parent_location)
#     bins = parent_cooler.bins()[:]
#     # TO DO: slightly memory demanding, maybe just fetch subset of bins

#     ann1, ann2 = f"{annot}1", f"{annot}2"
#     ann_df = cooler.annotate(self.get_dataframe(), bins)
#     ann_df = ann_df[[ann1, ann2, self._alpha_mod]]

#     # Sort annotations alphabetically to make a triagular matrix later
#     ann_df[ann1], ann_df[ann2] = np.where(
#         ann_df[ann1] < ann_df[ann2],
#         (ann_df[ann1], ann_df[ann2]),
#         (ann_df[ann2], ann_df[ann1]),
#     )

#     out_df = pd.concat([process_table(ann_df, *i) for i in interv])

#     out_df.reset_index(drop=True, inplace=True)
#     out_df.rename(columns={self._alpha_mod: "num_pixels"}, inplace=True)

#     return out_df


# THRESHOLD VERSION OF ANNOTATION DYNAMICS
# def annotation_dynamics(self, annot: str, step: float = 0.05) -> pd.DataFrame:
#     """Placeholder"""

#     def process_table(table, lower, upper):
#         """Placeholder"""

#         ann1, ann2, alpha_col = table.columns  # Assumed for convenience

#         filt_table = table.loc[table[alpha_col] <= upper]
#         filt_table = filt_table.query(f"{alpha_col} > {lower}")

#         out = filt_table.groupby([ann1, ann2]).count()
#         out.reset_index(inplace=True)
#         out["alpha"] = upper

#         return out

#     alphas = [round_half_up(n, 2) for n in np.arange(0, 1, step)]
#     interv = [(alphas[i], alphas[i + 1]) for i in range(len(alphas) - 1)]

#     parent_store = self._table_uri.split("hicona_tables")[0].strip("/")
#     parent_location = self._store_uri
#     if parent_store:  # Non empty -> multires
#         parent_location += f"::{parent_store}"

#     print(parent_location)
#     parent_cooler = cooler.Cooler(parent_location)
#     bins = parent_cooler.bins()[:]

#     ann1, ann2 = f"{annot}1", f"{annot}2"
#     ann_df = cooler.annotate(self.get_dataframe(), bins)
#     ann_df = ann_df[[ann1, ann2, self._alpha_mod]]

#     # Sort annotations alphabetically to make a triagular matrix later
#     ann_df[ann1], ann_df[ann2] = np.where(
#         ann_df[ann1] < ann_df[ann2],
#         (ann_df[ann1], ann_df[ann2]),
#         (ann_df[ann2], ann_df[ann1]),
#     )

#     out_df = pd.concat([process_table(ann_df, *i) for i in interv])

#     out_df.reset_index(drop=True, inplace=True)
#     out_df.rename(columns={self._alpha_mod: "num_pixels"}, inplace=True)

#     return out_df

# CUMULATIVE VERSION OF ANNOTATION DYNAMICS
# def annotation_dynamics(
#     self,
#     annot: str,
#     alphas: float | list[float],
# ) -> pd.DataFrame:
#     """Placeholder"""

#     def process_table(table, alpha):
#         """Placeholder"""

#         ann1, ann2, alpha_col = table.columns  # Assumed for convenience
#         table.query(f"{alpha_col} <= {alpha}", inplace=True)
#         table_size = len(table)

#         out = table.groupby([ann1, ann2]).count()  # / table_size
#         print(alpha)
#         print(out)
#         out = out / table_size
#         out.reset_index(inplace=True)
#         out["alpha"] = alpha

#         return out

#     alphas = [alphas] if isinstance(alphas, float) else alphas
#     alphas.sort(reverse=True)

#     parent_store = self._table_uri.split("hicona_tables")[0].strip("/")
#     parent_location = self._store_uri
#     if parent_store:  # Non empty -> multires
#         parent_location += f"::{parent_store}"

#     parent_cooler = cooler.Cooler(parent_location)
#     bins = parent_cooler.bins()[:]

#     ann1, ann2 = f"{annot}1", f"{annot}2"
#     ann_df = cooler.annotate(self.get_dataframe(), bins)
#     ann_df = ann_df[[ann1, ann2, self._alpha_mod]]

#     # Sort annotations alphabetically to make a triagular matrix later
#     ann_df[ann1], ann_df[ann2] = np.where(
#         ann_df[ann1] < ann_df[ann2],
#         (ann_df[ann1], ann_df[ann2]),
#         (ann_df[ann2], ann_df[ann1]),
#     )

#     out_df = pd.concat([process_table(ann_df, a) for a in alphas])
#     out_df.reset_index(drop=True, inplace=True)
#     out_df.rename(columns={self._alpha_mod: "fraction"}, inplace=True)

#     return out_df
