[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "hicona"
dynamic = ["version"]
authors = [
    { name = "Leonardo Morelli", email = "leo.morelli0@gmail.com" },
    { name = "Stefano Cretti", email = "stefanocretti99@gmail.com" },
]
description = "Network analysis toolkit for Hi-C data."
readme = "README.rst"

license = { file = "LICENSE" }
# keywords = []
# classifiers = []

dependencies = [
    "cooler",
    "polars",
    "pyarrow",
    "bioframe",
    "seaborn",
    "coolbox==0.4.0",
    "cooltools",
]

[project.optional-dependencies]
docs = ["nbsphinx", "sphinx", "sphinx_rtd_theme"]

# [project.urls]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]

[tool.hatch.version]
source = "vcs"


[tool.hatch.envs.default]
dependencies = ["pip"]

[tool.coverage.report]
exclude_also = ["if TYPE_CHECKING:"]
