"""Operations on bed-like files (e.i. any operation using bedtools)."""

import pandas as pd
import polars as pl
import pybedtools as pybed

from hicona._constants import BASE_BINS_COLS


def bed_to_df(
    bed: str | pybed.BedTool,
    col_names: tuple[str | None, ...] | None = None,
) -> pl.DataFrame:
    """Convert bed file to Dataframe, with custom column names.

    Provided colnames should skip the base columns (chrom, start, end).
    Columns for which no name is provided (None) are removed.
    """

    if isinstance(bed, str):
        bed = pybed.BedTool(bed)

    col_names = col_names or tuple()
    num_annot = int(bed.field_count()) - len(col_names) - 3
    col_names = BASE_BINS_COLS + col_names + (None,) * num_annot

    dataf = bed.to_dataframe(
        disable_auto_names=True,
        comment="#",
        header=None,
    )
    assert isinstance(dataf, pd.DataFrame)

    dataf = (
        pl.DataFrame(dataf)
        .select([str(c) for c, n in enumerate(col_names) if n is not None])
        .rename({str(c): n for c, n in enumerate(col_names) if n is not None})
    )

    str_cols = [
        col
        for col in dataf.columns
        if dataf[col].dtype == pl.String and col not in BASE_BINS_COLS
    ]

    dataf = dataf.with_columns(
        pl.when(pl.col(str_cols) == ".")
        .then(None)
        .otherwise(pl.col(str_cols))
        .name.keep()
    )

    return dataf


def get_intersection_names(
    df_a: pl.DataFrame,
    df_b: pl.DataFrame,
    new_cols: tuple[str | None, ...],
) -> tuple[str | None, ...]:
    """Returns the names to use for the intersection dataframe.
    new_cols are the names of the columns generated by the intersection (-wao, etc).
    Names start after the base columns (chrom, start, end).
    """

    colnames: tuple[str | None, ...] = tuple()
    colnames += tuple(col for col in df_a.columns if col not in BASE_BINS_COLS)
    colnames += (None, None, None)
    colnames += tuple(col for col in df_b.columns if col not in BASE_BINS_COLS)
    colnames += new_cols

    return colnames


def intersect_dfs(
    df_a: pl.DataFrame,
    df_b: pl.DataFrame,
    inters_names: tuple[str | None, ...],
    **kwargs,
):
    """Return dataframe intersection using bedtools intersect and fix colnames.

    Annotation interval columns (chrom, start, end) are removed from the output.
    Intersection names are the names of the columns generated by the intersection.
    """

    bed_a = pybed.BedTool.from_dataframe(df_a.to_pandas())
    bed_b = pybed.BedTool.from_dataframe(df_b.to_pandas())
    bed_a = bed_a.intersect(bed_b, **kwargs)  # pylint: disable=E1121 #type: ignore

    col_names = get_intersection_names(df_a, df_b, inters_names)
    return bed_to_df(bed_a, col_names)


def ann_fraction(
    query: pl.DataFrame,
    annotation: pl.DataFrame,
    anno_col: str,
    frac_col: str,
    nan_annot: str = "NaN",
) -> pl.DataFrame:
    """Get fraction of bases with given annotation in an interval."""

    # Intersect with the bed annotation and compute fraction of bin covered
    # by each annotation. Replace gaps with the nan annotation.
    dataf = intersect_dfs(query, annotation, (frac_col,), wao=True).with_columns(
        pl.col(anno_col).fill_null(nan_annot),
        (pl.col(frac_col) / (pl.col("end") - pl.col("start"))),
    )

    # Each bin should have a fraction of 1. If not, create a row with the
    # missing fraction and the nan annotation as the annotation.
    # NOTE: To my knowledge, chromHMM should cover the entire genome, which
    # does not happen all the time somehow. This is to fix that.

    missing = (
        dataf.group_by(BASE_BINS_COLS)
        .agg((pl.lit(1) - pl.col(frac_col).sum()).alias(frac_col))
        .with_columns(pl.lit(nan_annot).alias(anno_col))
        .filter(pl.col(frac_col) > 0)
        .select(BASE_BINS_COLS + (anno_col, frac_col))
    )

    # Add the missing fractions to the original dataframe, combine rows with the
    # same annotation for a bin (e.i. maybe two promoters) and sort the dataframe.
    inters = (
        pl.concat([dataf, missing])
        .group_by(BASE_BINS_COLS + (anno_col,))
        .agg(pl.col(frac_col).sum())
        .sort(BASE_BINS_COLS)
    )

    return inters


def ann_enriched(
    query: pl.DataFrame,
    ref: pl.DataFrame,
    anno_col: str,
    frac_col: str,
) -> pl.DataFrame:
    """Keep highest fold change annotation with respect to the background."""

    # Need to rename the columns to avoid conflicts during the intersection
    anno_bkg, frac_bkg = f"{anno_col}_bkg", f"{frac_col}_bkg"
    ref = ref.rename({anno_col: anno_bkg, frac_col: frac_bkg})

    # TODO: Do not know the behavior with ties. Should test.
    inters = (
        intersect_dfs(query, ref, (), loj=True)
        .filter(pl.col(anno_col) == pl.col(anno_bkg))
        .with_columns((pl.col(frac_col) / pl.col(frac_bkg)).alias("fold"))
        .filter(pl.col("fold") == pl.col("fold").max().over(BASE_BINS_COLS))
        .select(BASE_BINS_COLS + (anno_col,))
    )

    return inters
